server:
 port: 808
logging:
  config: classpath:log4j2.yml
spring:
 datasource:
  name: test
  url: jdbc:mysql://127.0.0.1:3306/dev_test
  username: root
  password: 
  # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  filters: stat
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20
 thymeleaf:
  cache: true
  check-template-location: true
  enabled: true
  encoding: utf-8
  mode: HTML5
  prefix: classpath:/templates/
  suffix: .html
  servlet:
   content-type: text/html
## 该配置节点为独立的节点
mybatis:
 mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
 type-aliases-package: com.demoone.DTO  # 注意：对应实体类的路径
